`timescale 1ns / 1ps
`include "defs.vh"

// ============================================================================
// Module: TopModule
// Description: Main top-level controller for the hardware accelerator. 
//              It orchestrates the Finite State Machine (FSM), memory fetch 
//              operations, training/inference data paths, and interconnects 
//              all processing sub-modules.
// ============================================================================
module TopModule(
    input CLK, 
    input RSTN, 
    
    // --- BRAM Interface ---
    input img_write_done,             // High when PS completes writing image to BRAM
    output reg [16:0] rd_addr,        // BRAM read address generated by PL
    
    // --- Standard Control & Data Ports ---
    input [`PIXELBITS-1:0] pixel,     // Pixel data fetched from BRAM
    input edge_count_en,              // Enable top-k edge mask extraction
    input edge_count_stop,            // Stop signal for edge counting phase
    input [3:0] class,                // Ground truth class label (for training)
    input train_en,                   // Training mode enable
    input train_last,                 // Indicates the last sample of the training batch
    input sort_en,                    // Enable sorting phase
    input prediction_en,              // Inference mode enable
    output reg [3:0] prediction,      // Final inference class output
    output reg prediction_valid,      // Inference output valid flag

    // =========================================================
    // Debug Output Ports for PYNQ AXI GPIO Interface
    // Exposes internal registers to the PS for real-time monitoring
    // =========================================================
    output [15:0] dbg_mask,
    output [71:0] dbg_data,
    output [8:0]  dbg_addr,
    output [15:0] dbg_score
    );
    
    // =========================================================
    // FSM State Definitions
    // =========================================================
    
    parameter IDLE         = 4'h0, // Idle / Wait for commands
              LOAD         = 4'h1, // Load image data for inference
              EDGE         = 4'h2, // Extract edges/features (Inference)
              EDGEWAIT     = 4'h3, // Wait for feature extraction pipeline
              SCORING      = 4'h4, // Calculate matching scores
              EDGETOPCOUNT = 4'h5, // Count and extract top-k edge masks
              LOADTR       = 4'h6, // Load image data for training
              EDGETR       = 4'h7, // Extract edges/features (Training)
              EDGEWAITTR   = 4'h8, // Wait for feature extraction (Training)
              COUNTING     = 4'h9, // Update occurrence counts in CAM emulation
              SORTING      = 4'hA; // Sort and finalize training weights
              
    parameter use_match = `USEMATCH;
    
    reg [15:0] counter;
    wire LOAD_done;
    wire EDGE_done;
    wire EDGEWAIT_done;
    wire SCORING_done;
    wire EDGETOPCOUNT_done;

    // Completion flags based on image size constants
    assign LOAD_done = (counter == `IMAGEARR1-1);
    assign EDGE_done = (counter == `IMAGEARR1-1);
    
    reg [3:0] state, next_state;
    
    // Flag to identify if the current state belongs to the training phase
    wire Training = (state==IDLE) | (state==LOADTR) | (state==EDGETR) | (state==EDGEWAITTR) | (state==COUNTING) | (state==SORTING);
    
    // Stores the top-k informative feature masks per class
    reg [15:0] top_masks [9:0]; 
    
    // Sequential BRAM read address generation
    always @(*) begin
        rd_addr = {1'b0, counter}; 
    end

    // =========================================================
    // Timing Correction for BRAM Read Latency
    // Delays the enable signal by 1 clock cycle to align with read data
    // =========================================================
    reg edge_count_en_d; 

    always @(posedge CLK or negedge RSTN) begin
        if (!RSTN) 
            edge_count_en_d <= 1'b0;
        else 
            edge_count_en_d <= edge_count_en; 
    end

    // =========================================================
    // Sub-module Instantiations
    // =========================================================
    
    
    // 1. EdgeCounter: Identifies and counts the most frequent edge patterns
    wire [15:0] top_mask_temp;
    wire top_mask_valid;
    
    EdgeCounter EdgeCounter_inst(
        .CLK(CLK), 
        .en(edge_count_en_d),       // Latency-compensated enable signal
        .pixel(pixel), 
        .top_filter_en(edge_count_stop), 
        .top_mask(top_mask_temp), 
        .top_mask_valid(top_mask_valid)
    );
    
    // 2. Storage8x64: Local buffer for the incoming pixel stream
    wire [`PIXELBITS-1:0] storage_out;
    reg edge_en;
    Storage8x64 Storage8x64_inst(
        .CLK(CLK), 
        .idata(pixel), 
        .write_en(state==LOAD || state==LOADTR), 
        .write_addr(counter), 
        .read_en(edge_en), 
        .read_addr(counter), 
        .odata(storage_out)
    );
    
    // 3. EdgeModule: Executes parallel edge and feature extraction
    wire [14:0] edge_valids;
    wire [`PIXELBITS*15-1:0] edge_outs;
    EdgeModule EdgeModule_inst(
        .CLK(CLK), 
        .RSTN(RSTN), 
        .en(edge_en), 
        .use_match(use_match==1'b1), 
        .idata(storage_out), 
        .valids(edge_valids), 
        .odatas(edge_outs)
    );
    
    // 4. QImageBuffer: Quantization and buffering for 15 parallel feature maps
    wire [14:0] score_readyarr;
    wire score_ready;
    assign score_ready = &(score_readyarr); // High when all buffers are ready
    assign EDGEWAIT_done = score_ready;
    
    wire [49-1:0] quant_images [14:0];
    reg  [49-1:0] score_images [11:0];
    wire [3:0] class_temp;
    
    genvar j;
    generate
        for (j=0; j<15; j=j+1) begin: gen
            QImageBuffer QImageBuffer_inst(
                .CLK(CLK), 
                .stack_en(edge_valids[j]), 
                .pixel(edge_outs[j*`PIXELBITS +: `PIXELBITS]), 
                .image_valid(score_readyarr[j]), 
                .image(quant_images[j])
            );
        end
    endgenerate

    // =========================================================
    // Feature Masking / Routing Logic
    // Selects relevant quantized features based on the active top-k mask
    // =========================================================
    integer b;
    integer s_idx;
    always @(*) begin
        s_idx = 0;
        if (Training) begin
            // Training Mode: Route features based on the ground-truth class mask
            for (b = 1; b < 16; b = b + 1) begin
                if (top_masks[class][b]) begin
                    if (s_idx < 12) begin
                        score_images[s_idx] = quant_images[b-1];
                        s_idx = s_idx + 1;
                    end
                end
            end
        end
        else begin
            // Inference Mode: Route features based on the dynamically evaluated class mask
            for (b = 1; b < 16; b = b + 1) begin
                if (top_masks[class_temp][b]) begin
                    if (s_idx < 12) begin
                        score_images[s_idx] = quant_images[b-1];
                        s_idx = s_idx + 1;
                    end
                end
            end
        end
    end
    
    // 5. TrainingModule: Manages weight updates and sorting operations
    wire train_pulse;
    assign train_pulse = score_ready && (state == EDGEWAITTR);
    wire COUNTING_done;
    wire SORTING_done;
    wire infer_we;
    wire [8:0] infer_addr;
    wire [71:0] infer_data;
    wire [5:0] infer_sel;

    TrainingModule TrainingModule_inst(
        .CLK(CLK),
        .RSTN(RSTN),
        .train_pulse(train_pulse),
        .last_image_flag(train_last),
        .target_class(class),
        .image00(score_images[0]), 
        .image01(score_images[1]), 
        .image02(score_images[2]), 
        .image03(score_images[3]), 
        .image04(score_images[4]), 
        .image05(score_images[5]), 
        .image06(score_images[6]), 
        .image07(score_images[7]), 
        .image08(score_images[8]), 
        .image09(score_images[9]), 
        .image10(score_images[10]), 
        .image11(score_images[11]), 
        .infer_we(infer_we),
        .infer_addr(infer_addr),
        .infer_data(infer_data),
        .infer_sel(infer_sel),
        .sample_done(COUNTING_done), 
        .done(SORTING_done)
    );

    // 6. ScoringModule: Calculates inference scores using trained CAM data
    wire [15:0] scores_temp [9:0];
    wire score_valid;
    reg score_en;
    
    ScoringModule ScoringModule_inst(
        .CLK(CLK), 
        .RSTN(RSTN), 
        .image00(score_images[0]), 
        .image01(score_images[1]), 
        .image02(score_images[2]), 
        .image03(score_images[3]), 
        .image04(score_images[4]), 
        .image05(score_images[5]), 
        .image06(score_images[6]), 
        .image07(score_images[7]), 
        .image08(score_images[8]), 
        .image09(score_images[9]), 
        .image10(score_images[10]), 
        .image11(score_images[11]), 
        .xmask(49'd0), 
        .en(score_en), 
        .infer_we(infer_we), 
        .infer_addr(infer_addr), 
        .infer_data(infer_data), 
        .infer_sel(infer_sel), 
        .class(class_temp), 
        .scores({scores_temp[9], scores_temp[8], scores_temp[7], scores_temp[6], scores_temp[5], scores_temp[4], scores_temp[3], scores_temp[2], scores_temp[1], scores_temp[0]}), 
        .score_valid(score_valid)
    );
    
    // 7. ArgMax: Identifies the class with the highest matching score
    wire [15:0] max_score;
    wire [3:0] max_idx;
    wire max_valid;
    ArgMax ArgMax_inst(
        .CLK(CLK), 
        .en(score_valid), 
        .scores({scores_temp[9], scores_temp[8], scores_temp[7], scores_temp[6], scores_temp[5], scores_temp[4], scores_temp[3], scores_temp[2], scores_temp[1], scores_temp[0]}), 
        .max_val(max_score), 
        .max_idx(max_idx), 
        .valid(max_valid)
    );
    
    // =================================================================
    // Continuous Assignments for Debugging
    // Maps internal logic paths to PS-accessible GPIOs
    // =================================================================
    assign dbg_mask  = top_mask_temp;
    assign dbg_data  = infer_data;
    assign dbg_addr  = infer_addr;
    assign dbg_score = max_score;

    // =================================================================
    // Main FSM Sequential Logic & Datapath Counters
    // =================================================================
    always @(posedge CLK or negedge RSTN) begin
        if (!RSTN) begin
            state <= IDLE;
            counter <= 0;
            edge_en <= 0;
            prediction <= 0;
            prediction_valid <= 0;
            score_en <= 0;
        end
        else begin
            state <= next_state;
            prediction <= max_idx;
            prediction_valid <= max_valid;
            
            score_en <= (next_state==SCORING) && (state==EDGEWAIT);
            
            // 1. Image Loading Phase
            if (state==LOAD || state==LOADTR) begin
                if (counter==`IMAGEARR1-1) begin
                    counter <= 0;
                    edge_en <= 1'b1;
                end
                else begin
                    counter <= counter + 1;
                end
            end
            
            // 2. Edge/Feature Processing Phase
            else if (state==EDGE || state==EDGETR) begin
                if (counter==`IMAGEARR1-1) begin
                    counter  <= 0;
                    edge_en <= 1'b0;
                end
                else begin
                    counter <= counter + 1;
                end
            end
            
            // 3. Top-k Edge Counting Phase 
            else if (state==EDGETOPCOUNT) begin
                if (edge_count_en) begin
                    if (counter==`IMAGEARR1-1) 
                        counter <= 0;
                    else 
                        counter <= counter + 1;
                end
                else begin
                    counter <= 0; // Reset address on Pause/Stop
                end

                if (top_mask_valid==1'b1) begin
                    top_masks[class] <= top_mask_temp;
                end
            end
            
            // 4. Default Reset
            else begin
                counter <= 0;
            end
        end
    end
    
    assign SCORING_done = prediction_valid;
    assign EDGETOPCOUNT_done = top_mask_valid;
    
    // =================================================================
    // FSM Combinational Next-State Logic
    // =================================================================
    always @(*) begin
        case (state)
            IDLE: begin
                if (img_write_done) 
                    next_state = train_en ? LOADTR : (prediction_en ? LOAD : IDLE);
                else if (edge_count_en) 
                    next_state = EDGETOPCOUNT;
                else 
                    next_state = IDLE;
            end
            LOAD:         next_state = LOAD_done ? EDGE : LOAD;
            EDGE:         next_state = EDGE_done ? EDGEWAIT : EDGE;
            EDGEWAIT:     next_state = score_ready ? SCORING : EDGEWAIT;
            SCORING:      next_state = SCORING_done ? IDLE : SCORING;
            EDGETOPCOUNT: next_state = EDGETOPCOUNT_done ? IDLE : EDGETOPCOUNT;
            LOADTR:       next_state = LOAD_done ? EDGETR : LOADTR;
            EDGETR:       next_state = EDGE_done ? EDGEWAITTR : EDGETR;
            EDGEWAITTR:   next_state = score_ready ? (train_last ? SORTING : COUNTING) : EDGEWAITTR;
            COUNTING:     next_state = COUNTING_done ? IDLE : COUNTING;
            SORTING:      next_state = SORTING_done ? IDLE : SORTING;
            default:      next_state = IDLE;
        endcase
    end
endmodule